run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple

issues:
  exclude-dirs:
    - vendor
  exclude-generated: strict
